name: Pysuite Integration Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: ${{matrix.task}} (Python ${{matrix.python_version}})
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - task: pypkg
            py_version: 3.6
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: set up python
        uses: actions/setup-python@v1
        with:
          python-version: ${{matrix.py_version}}
      - name: set up dependencies
        shell: bash
        run: |
          export TASK="${{ matrix.task }}"
          python -m pip install --upgrade pip
          $GITHUB_WORKSPACE/.ci/install.sh
      - name: run tests
        shell: bash
        run: |
          $GITHUB_WORKSPACE/.ci/test.sh

  all-successful:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Report Success
        run: echo "CI completed"
